spring:
  profiles:
    active: local # 기본 프로파일은 local로 설정

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: VZbs7eZweXVziCxAbFE5      # 네이버 클라이언트 ID
            client-secret: XAEJofXWGP          # 네이버 클라이언트 비밀번호
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  datasource:
    url: jdbc:mysql://localhost:3306/dearnote
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create

  jwt:
    secret-key: "asdfsadfasdfasddsaasdfasfasdfsafsadfsa"
    expiration-time: 86400000 # 1일

#  cloud:
#    aws:
#      region: ap-northeast-2
#      credentials:
#        access-key: ${DEV_S3_ACCESS_KEY}
#        secret-key: ${DEV_S3_SECRET_KEY}
#    s3:
#      bucket: dev-local-bucket
#    stack:
#      auto: false

springdoc:
  swagger-ui:
    path: /docs
