spring:
datasource:
  url: jdbc:mysql://localhost:3306/mydb
  username: ${LOCAL_DB_USERNAME}
  password: ${LOCAL_DB_PASSWORD}
  driver-class-name: com.mysql.cj.jdbc.Driver
sql:
  init:
    mode: never
jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      show_sql: true
      format_sql: true
      use_sql_comments: true
      hbm2ddl:
        auto: update
      default_batch_fetch_size: 1000

cloud:
  aws:
    region: ap-northeast-2
    credentials:
      access-key: ${DEV_S3_ACCESS_KEY}
      secret-key: ${DEV_S3_SECRET_KEY}
  s3:
    bucket: beat-dev-bucket
  stack:
    auto: false