spring:
  datasource:
    url: jdbc:mysql://${PROD_DB_HOST}:3306/mydb
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  jwt:
    secret-key: "asdfsadfasdfasddsaasdfasfasdfsafsadfsa"
    expiration-time: 86400000 # 1일

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ${NAVER_CLIENT_ID}     # 네이버 클라이언트 ID
            client-secret: ${NAVER_SECRET_ID}         # 네이버 클라이언트 비밀번호
            redirect-uri: http://${PROD_HOST}:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${DEV_S3_ACCESS_KEY}
      secret-key: ${DEV_S3_SECRET_KEY}
  s3:
    bucket: mybucket54
  stack:
    auto: false
